# Site settings
name: Joe Torreggiani
email: joetorreggiani@gmail.com
tag_line: "Thinking in systems. Building with purpose."
#canonical_url: https://edwinexemplar.com
keywords: "Senior Software Engineer, Ruby, TypeScript, React, Elixir, Fintech, Payroll, Systems Thinking, Open Source, Sustainability"
skills: "Engineer | Educator | Leader"
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/joetorreggiani/
  - title: medium
    url: https://medium.com/@jtorreggiani
  - title: github
    url: https://github.com/jtorreggiani

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: "171717"
  primary-rgb: "23, 23, 23"
  primary-light: "404040"
  primary-dark: "000000"
  secondary: "171717"
  secondary-dark: "000000"
  section-bg: "fafafa"

# Blog settings
excerpt_separator: "\n\n"

# Build settings
markdown: kramdown
permalink: pretty
port: 4077
